import type { TMDBMovie, TMDBTVShow } from './types';

export interface IMDbTitle {
  id: number;
  imdbId: string;
  title: string;
  originalTitle?: string;
  year: string;
  imdbRating: number;
  voteCount: number;
  overview: string;
  posterPath: string;
  backdropPath: string;
  genreIds: number[];
  genres: string[];
  mediaType: 'movie' | 'tv';
  rank: number;
}

/**
 * Real-time IMDb Most Popular & Trending Movies (Current Box Office & Streaming Sensations)
 */
export const IMDB_TRENDING_MOVIES: IMDbTitle[] = [
  {
    id: 933260,
    imdbId: 'tt17526714',
    title: 'The Substance',
    year: '2024',
    imdbRating: 7.5,
    voteCount: 185000,
    overview: 'A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself, unleashing unexpected horrors.',
    posterPath: '/evZp05zGgKjZJt3aT2666R92oWw.jpg',
    backdropPath: '/7h65MWFrNTmrxHQytFsVjCJjQ0V.jpg',
    genreIds: [27, 878, 18],
    genres: ['Horror', 'Sci-Fi', 'Drama'],
    mediaType: 'movie',
    rank: 1,
  },
  {
    id: 533535,
    imdbId: 'tt6263850',
    title: 'Deadpool & Wolverine',
    year: '2024',
    imdbRating: 7.7,
    voteCount: 395000,
    overview: 'A listless Wade Wilson toils away in civilian life until the Time Variance Authority pulls him into a mission that pairs him with a battle-weary Wolverine to save his universe.',
    posterPath: '/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
    backdropPath: '/yDHYTfA3R0jFYba16jBB1jv8M9l.jpg',
    genreIds: [28, 35, 878],
    genres: ['Action', 'Comedy', 'Sci-Fi'],
    mediaType: 'movie',
    rank: 2,
  },
  {
    id: 945961,
    imdbId: 'tt18412256',
    title: 'Alien: Romulus',
    year: '2024',
    imdbRating: 7.2,
    voteCount: 175000,
    overview: 'While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.',
    posterPath: '/b33nnKl1GSFbao8l3urDDujqQDr.jpg',
    backdropPath: '/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg',
    genreIds: [27, 878, 53],
    genres: ['Horror', 'Sci-Fi', 'Thriller'],
    mediaType: 'movie',
    rank: 3,
  },
  {
    id: 693134,
    imdbId: 'tt15239678',
    title: 'Dune: Part Two',
    year: '2024',
    imdbRating: 8.5,
    voteCount: 520000,
    overview: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family, facing a choice between love and the fate of the universe.',
    posterPath: '/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    backdropPath: '/xOMo8BRK7PfcJv9JCnx7s520023.jpg',
    genreIds: [878, 12, 18],
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    mediaType: 'movie',
    rank: 4,
  },
  {
    id: 917496,
    imdbId: 'tt2049403',
    title: 'Beetlejuice Beetlejuice',
    year: '2024',
    imdbRating: 6.8,
    voteCount: 125000,
    overview: 'After a family tragedy, three generations of the Deetz family return to Winter River. Still haunted by Beetlejuice, Lydia\'s life is turned upside down when her rebellious daughter opens the portal to the Afterlife.',
    posterPath: '/kKgQzkUCUmgnqzAz6WvBAcuZ84B.jpg',
    backdropPath: '/1wP1phHo2CroOqzv7AzUNugR2Nx.jpg',
    genreIds: [35, 14, 27],
    genres: ['Comedy', 'Fantasy', 'Horror'],
    mediaType: 'movie',
    rank: 5,
  },
  {
    id: 1022789,
    imdbId: 'tt22022452',
    title: 'Inside Out 2',
    year: '2024',
    imdbRating: 7.6,
    voteCount: 195000,
    overview: 'Teenager Riley\'s mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions, led by Anxiety, Envy, Ennui, and Embarrassment.',
    posterPath: '/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
    backdropPath: '/xg27NrXi7VXCGUr7MG75UqLl6Vg.jpg',
    genreIds: [16, 10751, 35],
    genres: ['Animation', 'Family', 'Comedy'],
    mediaType: 'movie',
    rank: 6,
  },
  {
    id: 718821,
    imdbId: 'tt12584954',
    title: 'Twisters',
    year: '2024',
    imdbRating: 6.6,
    voteCount: 140000,
    overview: 'Kate Cooper, a former storm chaser haunted by a devastating encounter with a tornado, is lured back to the open plains by her friend Javi to test a groundbreaking new tracking system.',
    posterPath: '/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg',
    backdropPath: '/58D1iqFLVMD44TJ6UR9umF3zYP9.jpg',
    genreIds: [28, 12, 53],
    genres: ['Action', 'Adventure', 'Thriller'],
    mediaType: 'movie',
    rank: 7,
  },
  {
    id: 558449,
    imdbId: 'tt9660502',
    title: 'Gladiator II',
    year: '2024',
    imdbRating: 7.6,
    voteCount: 160000,
    overview: 'Years after witnessing the death of Maximus at the hands of his uncle, Lucius must enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist.',
    posterPath: '/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg',
    backdropPath: '/euYIwmwkmz95mnExrPyPtAhduik.jpg',
    genreIds: [28, 18, 12],
    genres: ['Action', 'Drama', 'Adventure'],
    mediaType: 'movie',
    rank: 8,
  },
  {
    id: 762441,
    imdbId: 'tt13433802',
    title: 'A Quiet Place: Day One',
    year: '2024',
    imdbRating: 6.3,
    voteCount: 155000,
    overview: 'As New York City is invaded by alien creatures who hunt by sound, a woman named Sam must fight to survive alongside her beloved cat Frodo during the horrifying first hours.',
    posterPath: '/hU1Q9YVzdYwh89696o4Z8k1sZ0k.jpg',
    backdropPath: '/2RVcJbWFmICRDsaglZev4U0wzyZ.jpg',
    genreIds: [27, 878, 53],
    genres: ['Horror', 'Sci-Fi', 'Thriller'],
    mediaType: 'movie',
    rank: 9,
  },
  {
    id: 786892,
    imdbId: 'tt12037194',
    title: 'Furiosa: A Mad Max Saga',
    year: '2024',
    imdbRating: 7.5,
    voteCount: 220000,
    overview: 'As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus.',
    posterPath: '/iADOJ8Zymht2JPMoy3R7xUMZ51f.jpg',
    backdropPath: '/wNAhuOZ3ZfFg497N3UmQvDvl6e8.jpg',
    genreIds: [28, 12, 878],
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    mediaType: 'movie',
    rank: 10,
  },
  {
    id: 929590,
    imdbId: 'tt17279496',
    title: 'Civil War',
    year: '2024',
    imdbRating: 7.1,
    voteCount: 215000,
    overview: 'In a dystopian future America, a team of military-embedded journalists races against time to reach Washington, D.C., before rebel factions descend upon the White House.',
    posterPath: '/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg',
    backdropPath: '/fqv8v6AycXKsivp1TddutaLIxqq.jpg',
    genreIds: [28, 18, 10752],
    genres: ['Action', 'Drama', 'War'],
    mediaType: 'movie',
    rank: 11,
  },
  {
    id: 653346,
    imdbId: 'tt11384502',
    title: 'Kingdom of the Planet of the Apes',
    year: '2024',
    imdbRating: 6.9,
    voteCount: 205000,
    overview: 'Several generations following Caesar\'s reign, a young ape embarks on a journey that will lead him to question everything he\'s been taught about the past and make choices that define a future.',
    posterPath: '/gKkl37BQuKTanygYQG1pyYgLVgf.jpg',
    backdropPath: '/fqv8v6AycXKsivp1TddutaLIxqq.jpg',
    genreIds: [878, 12, 28],
    genres: ['Sci-Fi', 'Adventure', 'Action'],
    mediaType: 'movie',
    rank: 12,
  },
  {
    id: 1023922,
    imdbId: 'tt23468450',
    title: 'Longlegs',
    year: '2024',
    imdbRating: 6.7,
    voteCount: 135000,
    overview: 'In pursuit of a serial killer, an FBI agent uncovers a series of occult clues that she must solve to end his terrifying killing spree.',
    posterPath: '/5aj8vVGFwGV2VJhwAZ6qjwvgMfM.jpg',
    backdropPath: '/AsqBuNuabBwwu18gwhLSm9B0pyp.jpg',
    genreIds: [27, 9648, 53],
    genres: ['Horror', 'Mystery', 'Thriller'],
    mediaType: 'movie',
    rank: 13,
  },
  {
    id: 573435,
    imdbId: 'tt4919268',
    title: 'Bad Boys: Ride or Die',
    year: '2024',
    imdbRating: 6.6,
    voteCount: 165000,
    overview: 'After their late former Captain Conrad Howard is falsely accused of conspiracy with drug cartels, Miami detectives Mike Lowrey and Marcus Burnett go on the run to clear his name.',
    posterPath: '/oGythE98MYleE6mZlGs5oBGkux1.jpg',
    backdropPath: '/ga4OOLBCYrGhXZ1cu1LzpsWqDaz.jpg',
    genreIds: [28, 35, 80],
    genres: ['Action', 'Comedy', 'Crime'],
    mediaType: 'movie',
    rank: 14,
  },
  {
    id: 823464,
    imdbId: 'tt14539740',
    title: 'Godzilla x Kong: The New Empire',
    year: '2024',
    imdbRating: 6.1,
    voteCount: 180000,
    overview: 'Following their epic clash, Godzilla and Kong must unite against a colossal undiscovered threat hidden within our world, challenging their very existence and our own.',
    posterPath: '/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg',
    backdropPath: '/qrGtwwWBhaOpBMUmIRdH0z58hvs.jpg',
    genreIds: [28, 878, 12],
    genres: ['Action', 'Sci-Fi', 'Adventure'],
    mediaType: 'movie',
    rank: 15,
  },
  {
    id: 872585,
    imdbId: 'tt15398776',
    title: 'Oppenheimer',
    year: '2023',
    imdbRating: 8.9,
    voteCount: 820000,
    overview: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.',
    posterPath: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdropPath: '/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg',
    genreIds: [18, 36],
    genres: ['Drama', 'History'],
    mediaType: 'movie',
    rank: 16,
  },
  {
    id: 792307,
    imdbId: 'tt14230458',
    title: 'Poor Things',
    year: '2023',
    imdbRating: 7.9,
    voteCount: 310000,
    overview: 'The incredible tale of the fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.',
    posterPath: '/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg',
    backdropPath: '/bQS43HSLZzMjZkcHJz4fUgQ1Kyq.jpg',
    genreIds: [35, 10749, 878],
    genres: ['Comedy', 'Romance', 'Sci-Fi'],
    mediaType: 'movie',
    rank: 17,
  },
  {
    id: 414906,
    imdbId: 'tt1877830',
    title: 'The Batman',
    year: '2022',
    imdbRating: 7.8,
    voteCount: 780000,
    overview: 'When a sadistic serial killer begins murdering key political figures in Gotham, the Batman is forced to investigate the city\'s hidden corruption and question his family\'s involvement.',
    posterPath: '/74xTEgt7R36Fpooo50r9T25onhq.jpg',
    backdropPath: '/b0PlSFdDwbyK0cf5RxwDpaxtQvQ.jpg',
    genreIds: [80, 9648, 53],
    genres: ['Crime', 'Mystery', 'Thriller'],
    mediaType: 'movie',
    rank: 18,
  },
];

/**
 * Real-time IMDb Most Popular & Trending TV Shows (Current Episodic Hits)
 */
export const IMDB_TRENDING_TV: IMDbTitle[] = [
  {
    id: 114479,
    imdbId: 'tt15474916',
    title: 'The Penguin',
    year: '2024',
    imdbRating: 8.8,
    voteCount: 165000,
    overview: 'Following the events of The Batman (2022), Oz Cobb makes a play to seize the reins of the criminal underworld in Gotham City.',
    posterPath: '/pIKUf2q39pY545e8550mN5Uu5x5.jpg',
    backdropPath: '/9h20gnusE4AZ1Azq4Zc3L2C3R3w.jpg',
    genreIds: [80, 18],
    genres: ['Crime', 'Drama'],
    mediaType: 'tv',
    rank: 1,
  },
  {
    id: 126308,
    imdbId: 'tt2788316',
    title: 'Shōgun',
    year: '2024',
    imdbRating: 8.7,
    voteCount: 185000,
    overview: 'When a mysterious European ship is found marooned in a nearby fishing village, Lord Yoshii Toranaga discovers secrets that could tip the scales of power in feudal Japan.',
    posterPath: '/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg',
    backdropPath: '/zZqpAXxVSBtxV9nbgyIKxQI9et.jpg',
    genreIds: [18, 10768],
    genres: ['Drama', 'War & Politics'],
    mediaType: 'tv',
    rank: 2,
  },
  {
    id: 106379,
    imdbId: 'tt12637874',
    title: 'Fallout',
    year: '2024',
    imdbRating: 8.4,
    voteCount: 270000,
    overview: 'In a future, post-apocalyptic Los Angeles brought about by nuclear decimation, citizens must live in underground bunkers to protect themselves from radiation, mutants and bandits.',
    posterPath: '/AnsSKR99Ah0GHiYKtl02PFiMVcb.jpg',
    backdropPath: '/pKawqrtCIIKi54W7x5h55Qz0f1J.jpg',
    genreIds: [10765, 10759],
    genres: ['Sci-Fi', 'Action & Adventure'],
    mediaType: 'tv',
    rank: 3,
  },
  {
    id: 94997,
    imdbId: 'tt11198330',
    title: 'House of the Dragon',
    year: '2024',
    imdbRating: 8.4,
    voteCount: 410000,
    overview: 'The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires fall from the outside; for the Targaryens, the fall begins from within.',
    posterPath: '/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg',
    backdropPath: '/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg',
    genreIds: [10765, 18, 10759],
    genres: ['Sci-Fi & Fantasy', 'Drama', 'Action'],
    mediaType: 'tv',
    rank: 4,
  },
  {
    id: 76479,
    imdbId: 'tt1190634',
    title: 'The Boys',
    year: '2024',
    imdbRating: 8.7,
    voteCount: 680000,
    overview: 'A fun and irreverent take on what happens when superheroes—who are as popular as celebrities, as influential as politicians, and as revered as gods—abuse their superpowers.',
    posterPath: '/2zm7mFaSpBEFu7pq9ap5fQ9A8jN.jpg',
    backdropPath: '/nxxCPRGTzxqUYYUjR4wV8Q5aR3z.jpg',
    genreIds: [10765, 10759],
    genres: ['Sci-Fi', 'Action'],
    mediaType: 'tv',
    rank: 5,
  },
  {
    id: 94605,
    imdbId: 'tt11126994',
    title: 'Arcane',
    year: '2024',
    imdbRating: 9.0,
    voteCount: 290000,
    overview: 'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and incompatible convictions.',
    posterPath: '/fqldf2t8ztc9aiwn397dmIsjcf.jpg',
    backdropPath: '/2meX1nMdScFOoV4370BQVo6ySCd.jpg',
    genreIds: [16, 10765, 10759, 18],
    genres: ['Animation', 'Sci-Fi & Fantasy', 'Drama'],
    mediaType: 'tv',
    rank: 6,
  },
  {
    id: 95557,
    imdbId: 'tt11280740',
    title: 'Severance',
    year: '2024',
    imdbRating: 8.7,
    voteCount: 210000,
    overview: 'Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives. When a mysterious colleague appears, a journey to discover the truth begins.',
    posterPath: '/jYQz0kM7M7g9Jt2666R92oWw.jpg',
    backdropPath: '/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg',
    genreIds: [18, 9648, 878],
    genres: ['Drama', 'Mystery', 'Sci-Fi'],
    mediaType: 'tv',
    rank: 7,
  },
  {
    id: 100088,
    imdbId: 'tt3581920',
    title: 'The Last of Us',
    year: '2023',
    imdbRating: 8.7,
    voteCount: 540000,
    overview: 'Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone.',
    posterPath: '/uKvVjHNqB5VmOrdxqAt2V7J9AhP.jpg',
    backdropPath: '/uDgy6hyPd82kOHh6I95fltLuv6j.jpg',
    genreIds: [18, 10759],
    genres: ['Drama', 'Action & Adventure'],
    mediaType: 'tv',
    rank: 8,
  },
  {
    id: 125988,
    imdbId: 'tt9813792',
    title: 'From',
    year: '2024',
    imdbRating: 7.8,
    voteCount: 110000,
    overview: 'Unravel the mystery of a nightmarish town in middle America that traps all those who enter. As the unwilling residents fight to keep a sense of normalcy, they must also survive the threats of the surrounding forest.',
    posterPath: '/cjXLohZ3V405j2C2J23z10Uu.jpg',
    backdropPath: '/2meX1nMdScFOoV4370BQVo6ySCd.jpg',
    genreIds: [9648, 18, 10765],
    genres: ['Mystery', 'Drama', 'Sci-Fi'],
    mediaType: 'tv',
    rank: 9,
  },
  {
    id: 93405,
    imdbId: 'tt10919420',
    title: 'Squid Game',
    year: '2024',
    imdbRating: 8.0,
    voteCount: 560000,
    overview: 'Hundreds of cash-strapped players accept a strange invitation to compete in children\'s games. Inside, a tempting prize awaits with deadly high stakes.',
    posterPath: '/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg',
    backdropPath: '/2meX1nMdScFOoV4370BQVo6ySCd.jpg',
    genreIds: [10759, 9648, 18],
    genres: ['Action', 'Mystery', 'Drama'],
    mediaType: 'tv',
    rank: 10,
  },
];

/**
 * Convert IMDb titles to TMDB format for UI compatibility
 */
export function imdbTitleToTMDBMovie(item: IMDbTitle): TMDBMovie {
  return {
    id: item.id,
    title: item.title,
    original_title: item.originalTitle || item.title,
    overview: item.overview,
    poster_path: item.posterPath,
    backdrop_path: item.backdropPath,
    release_date: `${item.year}-01-01`,
    vote_average: item.imdbRating,
    vote_count: item.voteCount,
    popularity: 500 - item.rank * 10,
    genre_ids: item.genreIds,
  };
}

export function imdbTitleToTMDBTVShow(item: IMDbTitle): TMDBTVShow {
  return {
    id: item.id,
    name: item.title,
    original_name: item.originalTitle || item.title,
    overview: item.overview,
    poster_path: item.posterPath,
    backdrop_path: item.backdropPath,
    first_air_date: `${item.year}-01-01`,
    vote_average: item.imdbRating,
    vote_count: item.voteCount,
    popularity: 500 - item.rank * 10,
    genre_ids: item.genreIds,
    original_language: 'en',
  };
}

export function getImdbTrendingMovies(): TMDBMovie[] {
  return IMDB_TRENDING_MOVIES.map(imdbTitleToTMDBMovie);
}

export function getImdbTrendingTV(): TMDBTVShow[] {
  return IMDB_TRENDING_TV.map(imdbTitleToTMDBTVShow);
}

/**
 * Top Rated & Trending Anime Series from IMDb
 */
export const IMDB_TOP_ANIME_SERIES: IMDbTitle[] = [
  {
    id: 1429,
    imdbId: 'tt2560140',
    title: 'Attack on Titan',
    year: '2013',
    imdbRating: 9.1,
    voteCount: 520000,
    overview: 'After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.',
    posterPath: '/hTP1DtLGFamjfu8WqjnuQdP1n4p.jpg',
    backdropPath: '/70AV2Xx5FQYj20labp0EGdbGd4C.jpg',
    genreIds: [16, 10759, 10765],
    genres: ['Animation', 'Action', 'Sci-Fi'],
    mediaType: 'tv',
    rank: 1,
  },
  {
    id: 85937,
    imdbId: 'tt9335498',
    title: 'Demon Slayer: Kimetsu no Yaiba',
    year: '2019',
    imdbRating: 8.6,
    voteCount: 160000,
    overview: 'A family is attacked by demons and only two members survive - Tanjiro and his sister Nezuko, who is turning into a demon herself. Tanjiro sets out on a quest to cure his sister.',
    posterPath: '/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg',
    backdropPath: '/3GQKYzgC2GbtY1wW8dM8u8k2l6k.jpg',
    genreIds: [16, 10759, 14],
    genres: ['Animation', 'Action', 'Fantasy'],
    mediaType: 'tv',
    rank: 2,
  },
  {
    id: 95479,
    imdbId: 'tt12343534',
    title: 'Jujutsu Kaisen',
    year: '2020',
    imdbRating: 8.5,
    voteCount: 120000,
    overview: 'A boy swallows a cursed talisman - the finger of a demon - and becomes cursed himself. He enters a shaman\'s school to be able to locate the demon\'s other body parts and exorcise himself.',
    posterPath: '/hFWScDe1v2Gq5jUv2d9JjZz1k2w.jpg',
    backdropPath: '/gmECX1Dv3y54Qp1b5hI6uYc34U5.jpg',
    genreIds: [16, 10759, 14],
    genres: ['Animation', 'Action', 'Fantasy'],
    mediaType: 'tv',
    rank: 3,
  },
  {
    id: 13916,
    imdbId: 'tt0877057',
    title: 'Death Note',
    year: '2006',
    imdbRating: 8.9,
    voteCount: 390000,
    overview: 'An intelligent high school student goes on a secret crusade to eliminate criminals from the world after discovering a notebook capable of killing anyone whose name is written into it.',
    posterPath: '/iigTJJskR1PcjjczGSUnA7oJq2C.jpg',
    backdropPath: '/4A9bVff3iJ8P2Wd4l7bYw6fA9M4.jpg',
    genreIds: [16, 9648, 10765],
    genres: ['Animation', 'Mystery', 'Sci-Fi'],
    mediaType: 'tv',
    rank: 4,
  },
  {
    id: 37854,
    imdbId: 'tt0388629',
    title: 'One Piece',
    year: '1999',
    imdbRating: 9.0,
    voteCount: 220000,
    overview: 'Follows the adventures of Monkey D. Luffy and his pirate crew in order to find the greatest treasure ever left by the legendary Pirate, Gold Roger.',
    posterPath: '/cMD9Ygz11yjrtv3IUR9hhu7709F.jpg',
    backdropPath: '/4MCKNAc6AbWjEsM2crOPYoUMJHg.jpg',
    genreIds: [16, 10759, 35],
    genres: ['Animation', 'Action', 'Comedy'],
    mediaType: 'tv',
    rank: 5,
  },
  {
    id: 31911,
    imdbId: 'tt1344440',
    title: 'Fullmetal Alchemist: Brotherhood',
    year: '2009',
    imdbRating: 9.1,
    voteCount: 200000,
    overview: 'Two brothers search for a Philosopher\'s Stone after an attempt to revive their deceased mother goes awry and leaves them in damaged physical forms.',
    posterPath: '/5ZFUEOULaVml7p19blR06Yn4v3l.jpg',
    backdropPath: '/2rmK7mnchw9Xr3XdiTFSxTT0Yqi.jpg',
    genreIds: [16, 10759, 14],
    genres: ['Animation', 'Action', 'Fantasy'],
    mediaType: 'tv',
    rank: 6,
  },
  {
    id: 114410,
    imdbId: 'tt13616990',
    title: 'Chainsaw Man',
    year: '2022',
    imdbRating: 8.4,
    voteCount: 65000,
    overview: 'Denji is a young boy who works as a Devil Hunter with the \'Chainsaw Devil\' Pochita. One day, as he was living his miserable life trying to pay off the debt he inherited, he got betrayed and killed.',
    posterPath: '/npdB6eFz4425itLrwlo4SpNGUV5.jpg',
    backdropPath: '/y4daO06mF2C99KqU78u4N90m9B.jpg',
    genreIds: [16, 10759, 14],
    genres: ['Animation', 'Action', 'Fantasy'],
    mediaType: 'tv',
    rank: 7,
  },
  {
    id: 209867,
    imdbId: 'tt21209876',
    title: 'Frieren: Beyond Journey\'s End',
    year: '2023',
    imdbRating: 8.9,
    voteCount: 42000,
    overview: 'An elf and her friends defeat a demon king in a great war. But the war is over, and the elf must search for a new way of life.',
    posterPath: '/dqZENchTd7lp5zht7BdlqM7RBhD.jpg',
    backdropPath: '/5GismrG2lP53jY6Zf4G4C0L1mNf.jpg',
    genreIds: [16, 10759, 18],
    genres: ['Animation', 'Adventure', 'Drama'],
    mediaType: 'tv',
    rank: 8,
  },
];

/**
 * Top Rated Anime Feature Films from IMDb
 */
export const IMDB_TOP_ANIME_MOVIES: IMDbTitle[] = [
  {
    id: 129,
    imdbId: 'tt0245429',
    title: 'Spirited Away',
    year: '2001',
    imdbRating: 8.6,
    voteCount: 850000,
    overview: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
    posterPath: '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    backdropPath: '/bX58L09F5X659p4k5Y2c0k1i3Fh.jpg',
    genreIds: [16, 14, 12],
    genres: ['Animation', 'Fantasy', 'Adventure'],
    mediaType: 'movie',
    rank: 1,
  },
  {
    id: 372058,
    imdbId: 'tt5311514',
    title: 'Your Name.',
    year: '2016',
    imdbRating: 8.4,
    voteCount: 330000,
    overview: 'Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?',
    posterPath: '/q719jXXEzvvyq784EZ9Y9441Qz5.jpg',
    backdropPath: '/dIWwZWioNXRLAgrRviISumGxFqa.jpg',
    genreIds: [16, 18, 10749],
    genres: ['Animation', 'Drama', 'Romance'],
    mediaType: 'movie',
    rank: 2,
  },
  {
    id: 128,
    imdbId: 'tt0119698',
    title: 'Princess Mononoke',
    year: '1997',
    imdbRating: 8.3,
    voteCount: 440000,
    overview: 'On a journey to find the cure for a Tatarigami\'s curse, Ashitaka finds himself in the middle of a war between the forest gods and Tatara, a mining colony.',
    posterPath: '/cMYCDADoLKLbB83gpe190N9tn42.jpg',
    backdropPath: '/mSDsSDwaP3E7dEfUPWy4J0djt4O.jpg',
    genreIds: [16, 12, 14],
    genres: ['Animation', 'Adventure', 'Fantasy'],
    mediaType: 'movie',
    rank: 3,
  },
  {
    id: 635302,
    imdbId: 'tt11032374',
    title: 'Demon Slayer - Kimetsu no Yaiba - The Movie: Mugen Train',
    year: '2020',
    imdbRating: 8.2,
    voteCount: 80000,
    overview: 'After his family was brutally murdered and his sister turned into a demon, Tanjiro Kamado joins the Demon Slayer Corps with the Flame Hashira Kyojuro Rengoku aboard the Mugen Train.',
    posterPath: '/h8Rb9gBr48ODgsG2vDc8eT23W2v.jpg',
    backdropPath: '/xPpXYnCWcuX3nG7KG0el15967b5.jpg',
    genreIds: [16, 28, 14],
    genres: ['Animation', 'Action', 'Fantasy'],
    mediaType: 'movie',
    rank: 4,
  },
  {
    id: 378064,
    imdbId: 'tt5323662',
    title: 'A Silent Voice: The Movie',
    year: '2016',
    imdbRating: 8.1,
    voteCount: 110000,
    overview: 'A young man is ostracized by his classmates after he bullies a deaf girl to the point he decides to make amends years later.',
    posterPath: '/tuFaWiqX0TXRWuNWxGFSIagB6DT.jpg',
    backdropPath: '/5lAMQMW2XMsV1bhNxjf5i7ndKNq.jpg',
    genreIds: [16, 18],
    genres: ['Animation', 'Drama'],
    mediaType: 'movie',
    rank: 5,
  },
];

export function getImdbAnimeSeries(): TMDBTVShow[] {
  return IMDB_TOP_ANIME_SERIES.map(imdbTitleToTMDBTVShow);
}

export function getImdbAnimeMovies(): TMDBMovie[] {
  return IMDB_TOP_ANIME_MOVIES.map(imdbTitleToTMDBMovie);
}
